type = "service_account"
project_id = "warm-physics-474702-q3"
private_key_id = "31ae992c43e32ea9cc9056642181ae7007f5b461"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4DcutA6uVYKqz
NfIden8q4QZbulk5yHRJVEgUO28/ylaNL9gYtm9eO5V7+UU8mNxn0xXOEbacQykk
l6UrDcfcg8yLLJKfaL1ff9M3bZo8VfGGNSk1WWxFruv9e8chi5lSV4nPz2jA6YDU
0Ql9G421QhD66zQ0PrNvMGX4D/rxAc8WDLh09e7xpDWcoaJQfV6uy+/iatS6tDLW
ACKVHjM8W57uDnXmjtM08aW+Gng35bpc4p1qnfLYdhkC4t/jI5FJ8tULgVnbjCxP
SJDIRjkbOVXcsYMtkgwR+Hq8+2dYd81wsWotEohQ390y3SDsM4HLk5iNoyx1fyZJ
P4pc5uPzAgMBAAECggEANyvDevhXra5NXOz1x4pZpkPPwR1J8703xmdiN9ZdEbUY
XrgRwc6l8YxQ0dm1vGVh5CltJtk+cPbc1WAznYVC/MHxRWK2DNy7r23EpZ/QFPf6
Ly2uTZShlP3LNa+t0EtlST5+S/GzR+h2utRyULM6tjO4nU511pdY+CJ83nAD28wZ
sz5Y+xvSIc+FCHQbhYnFXZkTPlF0pbMIb5PWmBhzcdLDDVZxgYdUvxwZPxhz+75C
gqbKHFZW+u/HS4Y3bc7OyZptYqsDBVPGzV+i0+gwI/wSDA9kA5hO4t87GFRZYtMw
cJ0OJvWNhQDfbGe7JLi42F23PUJeyb9qUPSS4b1tQQKBgQDk12JGLFjGmvHmLz28
ZvgL0NF2t41q3JrqROEOEHyVC3G1VKCU5jIS3grfL4IFW7vKaZEWwmHbtd72FX43
EysLbsN95Yf8AEdkIbXy1C5WkWfkhdUomrM6y4MRN3D/4kZtYwzwzPfil/gXRHk+
2rOVrrlg1GFrEK5sw9fkPblCIQKBgQDN5a/7V0ory/hDrGUO5ne4Y6KAQ64wRGYP
6W5VlZJJPIWctpzl3Mn55JsceEox1MxHK47DYaNl/zn/qSDpB8SL2GFhex2PAZVW
/HO3l47LgoE8EMx7D5oSMeF0hpp5t14zDwscmvhoanBSmbyefsGDt7+MOA56BRJZ
eb5IfN6LkwKBgC88pnSFwu18HmK9bajuOFV4DUTMLszYLMIe5bXZgV3itt4PUfZq
bfunCed4Dwa8IM9vaxuflEOeDyAM37jOpBwACSp7rs494H6y1rQBSG9mJGPvnEh9
ZnHEgJGVOCYZtx/tSkaKiMClTfi/kad/zYIgRvPN4y4Oi3K4GmBqvUsBAoGAPe0K
G98qGLgVKE1ua6fXdCbLViaE+lFoHPsJS0ZcJBjG2tZ1pBDe0oD2Qf7P2eL1uaYZ
Hxx7p4624/T7R/slGyZuS4Ja5osEXpA5QYuc0AqlUep/hbewkC5eb8yYI2mKNHMe
1XCqq8TvmXhRqZ3YGASo4MRvXjWuSij6mRStXm8CgYBk/TuIcJaFBOBP+Bd92Jm3
ucUo2TlWKXonGB1LOsMi+HhRO+P7ySlH++2UIC/BDmi+ZIG8p++64Pid18qElfOj
HGyAuoPZrbxthYNzo2rHSPkEjOl5K7EJeiMn9TlUW0WapzWIRM1h1qAk8qCGJMt/
ThJSKc/ya3OLsK4IfwprpA==
-----END PRIVATE KEY-----"""
client_email = "503514048499-compute@developer.gserviceaccount.com"
client_id = "114534562769198332747"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/503514048499-compute%40developer.gserviceaccount.com"
universe_domain = "googleapis.com"

[gcs]
bucket_name = "patentbucket-maam"
project_id = "warm-physics-474702-q3"
